methods to get logger_provider, config options or default to OTel values
kaylareopelle/opentelemetry-ruby-contrib pull request #4
Opened 2024-05-07 06:50 UTC by khushijain21

2024-05-09 01:19 UTC, kaylareopelle requested changes
Thank you for this PR!

So strange about the diff showing the entire file changed! Maybe resolving the merge conflicts would update the diff? I also updated the `logger-instrumentation` branch to include the latest upstream `main`. There was a merge conflict involving a deleted file. Perhaps that's playing a role too.

I have one request related to code relocation. Other than that, these changes look good to me. 

Could you add some tests for the new configuration options? There's some examples in the [postgres instrumentation](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb) with various config options. Our existing tests wouldn't cover these use cases. 

If you're not able to add tests with the time you have available, defining the cases that need to be seen, and skipping them with a message would also work at this stage. 

Something like this could work:
```ruby 
  def test_config_option_name_present
    skip 'TODO: write tests for configuration options'
  end 
```

2024-05-09 01:19 UTC, kaylareopelle commented on instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
> +          option :version, default: OpenTelemetry::Instrumentation::Logger::VERSION, validate: :string
I think these lines need to be in [logger/instrumentation.rb](https://github.com/kaylareopelle/opentelemetry-ruby-contrib/blob/logger-instrumentation/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb). [Here's an example for postgres instrumentation.](https://github.com/kaylareopelle/opentelemetry-ruby-contrib/blob/logger-instrumentation/instrumentation/pg/lib/opentelemetry/instrumentation/pg/instrumentation.rb#L27-L29)

2024-05-09 01:19 UTC, kaylareopelle commented on instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
> +            @skip_instrumenting || false # Set to a default value
Nice, good catch.

2024-05-10 02:37 UTC, kaylareopelle requested changes
Thank you for the updates!

The CI is failing due to the PR title not matching a conventional commit. Could you update the title to include one of [the conventional commit prefixes](https://www.conventionalcommits.org/en/v1.0.0/#summary)? This should allow the rest of the tests to run. 

On my machine, when I run `bundle exec rake test` from the `instrumentation/logger` directory, some of the existing tests aren't passing with the recent changes. I'd like to get things passing before merging this in. If things are passing on your machine, let's troubleshoot to see where the difference lies. I added a comment inline on the PR that seems to be the source of the problem.

Also, building from your TODO in the test file, I added a few tests for the name and version configuration option in https://github.com/khushijain21/opentelemetry-ruby-contrib/pull/2. We don't need to merge them in, they were just helpful for me to review the code. 

I am having some trouble understanding how someone would set their own logger provider for this bridge. Could you describe the steps a user would take to pass their own logger provider?

2024-05-10 02:37 UTC, kaylareopelle commented on instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
> +              version: @config[:version]
When I run the tests locally, I see errors related to these lines. Do you get errors on your machine as well?

2024-05-13 07:03 UTC, khushijain21 commented
> I am having some trouble understanding how someone would set their own logger provider for this bridge. Could you describe the steps a user would take to pass their own logger provider?

The idea is similar to how we set skip instrumenting, the user can set the instance variable like this
`ruby_logger.logger_provider = customLoggerProvider`

2024-05-14 01:59 UTC, kaylareopelle commented
> The idea is similar to how we set skip instrumenting, the user can set the instance variable like this
ruby_logger.logger_provider = customLoggerProvider 

Ah, thank you. I don't think that'll be easily accessed by the customer. It would involve intimate knowledge about the bridge that we don't expect users to have. Allowing the user to set it via another configuration `option` method would be a more standardized approach. Would you be comfortable adding an `option` to set a logger provider?

2024-05-14 02:48 UTC, kaylareopelle requested changes
Nice config refactor! The only change that has to happen as part of this PR is the one related to `context`. 

🤞 I think all the action mailer stuff should go away after the merge conflicts are resolved.

Like I mentioned in my comment on the main page, I think we need to allow users to set the logger provider through a configuration `option`. 

Once `context` is fixed, I think we could merge this PR. However, there would need to be a follow up updating the code for setting a logger provider. I think I would prefer to pull the logger provider changes out of this branch and have them tackled in a separate PR, however, I know time is in short supply. What works best for you?

2024-05-14 02:48 UTC, kaylareopelle commented on instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
> +              version: Instrumentation.instance.config[:version]
Nice adjustment!

2024-05-14 02:48 UTC, kaylareopelle commented on instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
> +              context: OpenTelemetry::Context.Current
```suggestion
              context: OpenTelemetry::Context.current
```

Small typo. Though Ruby methods can start with capital letters, they usually start with lowercase ones. This one follows the convention. I think we talked about this in Slack and I forgot to bring it up then.

2024-05-14 02:48 UTC, kaylareopelle commented on instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
> +          end
Since these are generic setters, you can rewrite them to `attr_writer :logger_provider, :skip_instrumenting`, after the `module Logger` line.

2024-05-14 02:48 UTC, kaylareopelle commented on instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
> +          end
I need to think about this one a little more. The `OpenTelemetry.logger_provider` method relies on a [Mutex](https://workingwithruby.com/wwrt/mutex/) and [memoizing it](https://blog.appsignal.com/2022/12/20/a-guide-to-memoization-in-ruby.html) may cause some problems.

2024-05-14 02:48 UTC, kaylareopelle commented on instrumentation/logger/test/test_helper.rb
> +  # enable_coverage :branch
Could you un-comment this?

2024-05-14 03:52 UTC, khushijain21 commented
I removed logger_provider out of this PR. Not sure why so many file changes show up here. :/

2024-05-14 18:11 UTC, kaylareopelle commented
> I removed logger_provider out of this PR. Not sure why so many file changes show up here. :/

@khushijain21 I think the trouble is with the merge commits 😞 This is likely my fault for accidentally merging in the action mailer branch to the `logger-instrumentation` branch.

I can think of two paths to fix this:
* use `git rebase -i logger-instrumentation` to rebase interactively and remove the unrelated commits and force push (or `--force-with-lease`) the changes
* create a new branch off `logger-instrumentation` and cherry pick the commits from this branch you want to preserve and open a new PR against that branch.

I was able to re-create your work without the extra files/merge commits by running the following from a new branch made off `logger-instrumentation`:
```console
git cherry-pick 3bc6324467ab5d4964e42edda423f1467781f9a9 \
8f0076a0d6006644264a64a5d75421b08fbb4061 \
e66b8c3649782c6a23a274ef3fb015a4e006ebdb \
5b4026b6344d04d1a3359add5e0f9b2c398b69a3 \
794a8519b44a1959f131a070d5a18c5c2113a4f7
```

The diff comes out with what I believe we're looking for, but `OpenTelemetry::Context.Current` is still used instead of `OpenTelemetry::Context.current`: 
```diff
diff --git a/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb b/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb
index f87eef44..b89c6033 100644
--- a/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb
+++ b/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb
@@ -18,6 +18,9 @@ module OpenTelemetry
           defined?(::Logger)
         end

+        option :name, default: OpenTelemetry::Instrumentation::Logger::NAME, validate: :string
+        option :version, default: OpenTelemetry::Instrumentation::Logger::VERSION, validate: :string
+
         private

         def patch
diff --git a/instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb b/instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
index 129a64f1..143fb013 100644
--- a/instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
+++ b/instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
@@ -10,6 +10,8 @@ module OpenTelemetry
       module Patches
         # Instrumention for methods from Ruby's Logger class
         module Logger
+          attr_writer :skip_instrumenting
+
           # TODO: Make sure OTel logs aren't instrumented
           # TODO: How to pass attributes?
           def format_message(severity, datetime, progname, msg)
@@ -17,24 +19,22 @@ module OpenTelemetry
             return formatted_message if skip_instrumenting?

             OpenTelemetry.logger_provider.logger(
-              name: OpenTelemetry::Instrumentation::Logger::NAME,
-              version: OpenTelemetry::Instrumentation::Logger::VERSION
+              name: Instrumentation.instance.config[:name],
+              version: Instrumentation.instance.config[:version]
             ).on_emit(
               severity_text: severity,
               severity_number: severity_number(severity),
               timestamp: datetime,
-              body: msg # New Relic uses formatted_message here. This also helps us with not recording progname, because it is included in the formatted message by default. Which seems more appropr
iate?
+              body: msg, # New Relic uses formatted_message here. This also helps us with not reco
rding progname, because it is included in the formatted message by default. Which seems more approp
riate?
+              context: OpenTelemetry::Context.Current
             )
             formatted_message
           end

           private

-          # Placeholder for now
-          def instrumentation_config; end
-
           def skip_instrumenting?
-            instance_variable_get(:@skip_instrumenting)
+            @skip_instrumenting || false
           end

           def severity_number(severity)
diff --git a/instrumentation/logger/test/opentelemetry/instrumentation/logger/patches/logger_test.r
b b/instrumentation/logger/test/opentelemetry/instrumentation/logger/patches/logger_test.rb
index 33c70b4f..a5ced9d9 100644
--- a/instrumentation/logger/test/opentelemetry/instrumentation/logger/patches/logger_test.rb
+++ b/instrumentation/logger/test/opentelemetry/instrumentation/logger/patches/logger_test.rb
@@ -29,12 +29,17 @@ describe OpenTelemetry::Instrumentation::Logger::Patches::Logger do
       assert_match(/DEBUG -- : #{msg}/, log_stream.string)
     end

-    it 'sets the OTel logger instrumentation name and version' do
+    it 'sets the OTel logger instrumentation name and version (default case)' do
       ruby_logger.debug(msg)
       assert_equal(OpenTelemetry::Instrumentation::Logger::NAME, log_record.instrumentation_scope.
name)
       assert_equal(OpenTelemetry::Instrumentation::Logger::VERSION, log_record.instrumentation_sco
pe.version)
     end

+    it 'sets the OTel logger instrumentation name and version (user defined)' do
+      ruby_logger.debug(msg)
+      skip 'TODO: write tests for configuration options'
+    end
+
     it 'sets log record attributes based on the Ruby log' do
       timestamp = Time.now
       Time.stub(:now, timestamp) do
```

> I removed logger_provider out of this PR. Not sure why so many file changes show up here. :/

@khushijain21 I think the trouble is with the merge commits 😞 

I was able to re-create your work without the extra files/merge commits by running the following from a new branch made off `logger-instrumentation`:
```console
git cherry-pick 3bc6324467ab5d4964e42edda423f1467781f9a9 \
8f0076a0d6006644264a64a5d75421b08fbb4061 \
e66b8c3649782c6a23a274ef3fb015a4e006ebdb \
5b4026b6344d04d1a3359add5e0f9b2c398b69a3 \
794a8519b44a1959f131a070d5a18c5c2113a4f7
```

The diff comes out with what I believe we're looking for: 
```diff
diff --git a/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb b/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb
index f87eef44..b89c6033 100644
--- a/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb
+++ b/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb
@@ -18,6 +18,9 @@ module OpenTelemetry
           defined?(::Logger)
         end

+        option :name, default: OpenTelemetry::Instrumentation::Logger::NAME, validate: :string
+        option :version, default: OpenTelemetry::Instrumentation::Logger::VERSION, validate: :string
+
         private

         def patch
diff --git a/instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb b/instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
index 129a64f1..143fb013 100644
--- a/instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
+++ b/instrumentation/logger/lib/opentelemetry/instrumentation/logger/patches/logger.rb
@@ -10,6 +10,8 @@ module OpenTelemetry
       module Patches
         # Instrumention for methods from Ruby's Logger class
         module Logger
+          attr_writer :skip_instrumenting
+
           # TODO: Make sure OTel logs aren't instrumented
           # TODO: How to pass attributes?
           def format_message(severity, datetime, progname, msg)
@@ -17,24 +19,22 @@ module OpenTelemetry
             return formatted_message if skip_instrumenting?

             OpenTelemetry.logger_provider.logger(
-              name: OpenTelemetry::Instrumentation::Logger::NAME,
-              version: OpenTelemetry::Instrumentation::Logger::VERSION
+              name: Instrumentation.instance.config[:name],
+              version: Instrumentation.instance.config[:version]
             ).on_emit(
               severity_text: severity,
               severity_number: severity_number(severity),
               timestamp: datetime,
-              b [...]

2024-05-16 11:53 UTC, closed without merging